import React from 'react';
import Head from 'next/Head';

export default function Layout({title, children}) {
    return (
        <div className="bg-blue-300">
            <Head>
                <title>{title, children}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="container mx-auto max-w-xl pt-8 min-h-screen">
                {children}
            </main>
        </div>
    )
}